---
- name: Check if /opt/zoom/ZoomLauncher exists
  stat:
    path: /opt/zoom/ZoomLauncher
  register: stat_zoom_file

- name: Download and install Zoom DEB
  apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
  become: true 
  when: ansible_os_family == "Debian" and not stat_zoom_file.stat.exists

# note: this will fail on Rocky Linux. Here's the fix: https://forums.rockylinux.org/t/cannot-import-zooms-gpg-key/6598/9
# recommended fix: update-crypto-policies --set LEGACY *OR* update-crypto-policies --set DEFAULT:SHA1
# I'm not sure what the implications are, but I'm going to have to put a cmd.run here (probably for the 2nd command) when ansible_distribution == Rocky and ansible_distribution_major_version <= 9

- name: run update-crypto-policies to allow SHA1 for Rocky 9 and above
  command:
    cmd: update-crypto-policies --set DEFAULT:SHA1
  become: true
  when: ('Rocky' in ansible_distribution) and (ansible_distribution_major_version|int >= 9)

- name: Install Zoom RPM GPG key
  rpm_key:
    key: https://zoom.us/linux/download/pubkey?version=5-12-6
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Download and install Zoom RPM
  yum:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
  become: true
  when: ansible_os_family == "RedHat" and not stat_zoom_file.stat.exists
