---
- name: install zoom DEB package
  apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
  become: true
  when: "'Ubuntu' in ansible_distribution"

- name: add yum GPG key for Zoom RPM
  rpm_key:
    key: "https://zoom.us/linux/download/pubkey"
    state: present
  become: true
  when: "'Fedora' in ansible_distribution"

- name: install zoom RPM package
  yum:
    name: 
      - "https://zoom.us/client/latest/zoom_x86_64.rpm"
  become: true
  when: "'Fedora' in ansible_distribution"