---
- name: add yum GPG keys for rpmfusion (Fedora)
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020" # rpmfusion free
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020" # rpmfusion non-free
  become: true 
  when: "'Fedora' in ansible_distribution"

- name: add yum GPG keys for rpmfusion (Rocky)
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-9" # rpmfusion free
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-9" # rpmfusion non-free
  become: true 
  when: "'Rocky' in ansible_distribution"

- name: install the rpmfusion repo packages (Fedora)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  become: true
  when: "'Fedora' in ansible_distribution"

- name: install EPEL (Rocky)
  dnf:
    name: epel-release
    state: present
  become: true
  when: "'Rocky' in ansible_distribution"

- name: check if CRB already enabled (Rocky)
  command:
    cmd: grep -A5 \\[crb\\] /etc/yum.repos.d/rocky.repo | grep -q enabled=1
  register: crb_enabled
  changed_when: false
  ignore_errors: true
  when: "'Rocky' in ansible_distribution"

- name: Enable CRB repo (Rocky)
  command:
    cmd: dnf config-manager --enable crb
  become: true
  when: "'Rocky' in ansible_distribution and crb_enabled.false"

- name: install the rpmfusion repo packages (Rocky)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  become: true
  when: "'Rocky' in ansible_distribution"
