---
- name: install flatpak
  package:
    name: flatpak
    state: present
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items: "{{ flatpak_packages }}"
