- name: install terminator package
  apt:
    name:
      - terminator

- name: create config dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items:
    - ~/.config/terminator

- name: copy terminator config file
  copy:
    src: files/terminator-config
    dest: ~/.config/terminator/config
    mode: '0660'
