---
# this actually doesn't work in Debian Bullseye, at least not last time I tried, but I don't feel like fixing it (it'd be a lot of when logic)
# and Bullseye is running a fairly old GNOME stack anyhow, so... what's the point?
- name: install Slack DEB
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.28.184/prod/x64/slack-desktop-4.28.184-amd64.deb
  become: true 
  when: ansible_os_family == "Debian"

- name: add yum RPM GPG key for Slack
  rpm_key:
    key: "https://slack.com/gpg/slack_pubkey_20220708.gpg"
    state: present
  become: true 
  when: ansible_os_family == "RedHat"

- name: install Slack RPM
  yum:
    name: https://downloads.slack-edge.com/releases/linux/4.28.184/prod/x64/slack-4.28.184-0.1.el8.x86_64.rpm
  become: true
  when: ansible_os_family == "RedHat"

- name: create autostart directory
  file:
    path: ~/.config/autostart
    mode: '0775'
    state: directory

- name: start Slack on login
  copy:
    src: files/slack.desktop
    dest: ~/.config/autostart/slack.desktop
