---
# this actually doesn't work in Debian Bullseye, at least not last time I tried, but I don't feel like fixing it (it'd be a lot of when logic)
# and Bullseye is running a fairly old GNOME stack anyhow, so... what's the point?
- name: install Slack DEB
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.28.184/prod/x64/slack-desktop-4.28.184-amd64.deb
  become: true 
  when: ansible_os_family == "Debian"

- name: install Slack RPM
  yum:
    name: https://downloads.slack-edge.com/releases/linux/4.35.126/prod/x64/slack-4.35.126-0.1.el8.x86_64.rpm
  become: true 
  when: ansible_os_family == "RedHat"
