---
- name: install Slack DEB
  apt:
    deb: "https://downloads.slack-edge.com/releases/linux/4.27.156/prod/x64/slack-desktop-4.27.156-amd64.deb"
  become: true 
  when: ansible_os_family == "Debian"

# the slack client is no longer supported in Fedora as of March 2022
# the packagecloud workaround no longer installs, instead throwing an error about the GPG key
# either I have to run Ubuntu, or I have to use Slack in a web browser :manshrug:
- name: Add Slack packagecloud repo for Fedora
  yum_repository:
    name: slacktechnologies_slack
    description: Slack Technologies Packagecloud Repo
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
    gpgcheck: yes
    gpgkey: https://packagecloud.io/slacktechnologies/slack/gpgkey
    enabled: yes
  become: true
  when: "'Fedora' in ansible_distribution"

- name: add yum GPG key for Slack (Fedora)
  rpm_key:
    key: "https://packagecloud.io/slacktechnologies/slack/gpgkey"
    state: present
  become: true 
  when: "'Fedora' in ansible_distribution"

- name: install Slack from Packagecloud (fedora)
  yum:
    name: slack
  become: true
  when: "'Fedora' in ansible_distribution"

# fix this: will install on both Fedora *AND* RedHat/Rocky/etc
- name: install Slack RPM (Rocky Linux)
  yum:
    name: https://downloads.slack-edge.com/releases/linux/4.28.171/prod/x64/slack-4.28.171-0.1.el8.x86_64.rpm
  become: true
  when: ansible_distribution == "Rocky"

- name: create autostart directory
  file:
    path: ~/.config/autostart
    mode: '0775'
    state: directory

- name: start Slack on login
  copy:
    src: files/slack.desktop
    dest: ~/.config/autostart/slack.desktop
