---
- name: install Slack DEB
  apt:
    deb: "https://downloads.slack-edge.com/releases/linux/4.27.156/prod/x64/slack-desktop-4.27.156-amd64.deb"
  become: true 
  when: ansible_os_family == "Debian"

# TODO: fix this! it does not work on Ubuntu 22.04 or Debian, it fails.
#- name: Fedora - add COPR for Slack
#  community.general.copr:
#    host: copr.fedorainfracloud.org
#    state: enabled
#    name: jdoss/slack-repo
#  become: true
#  when: ansible_os_family == "RedHat"

- name: install Slack *REPO* RPM
  yum:
    name: slack-repo
  become: true
  when: ansible_os_family == "RedHat"

- name: install Slack RPM
  yum:
    name: slack
  become: true
  when: ansible_os_family == "RedHat"

- name: create autostart directory
  file:
    path: ~/.config/autostart
    mode: '0775'
    state: directory

- name: start Slack on login
  copy:
    src: files/slack.desktop
    dest: ~/.config/autostart/slack.desktop
