---
# this actually doesn't work in Debian Bullseye, at least not last time I tried, but I don't feel like fixing it (it'd be a lot of when logic)
# and Bullseye is running a fairly old GNOME stack anyhow, so... what's the point?
- name: install Slack DEB
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.28.184/prod/x64/slack-desktop-4.28.184-amd64.deb
  become: true 
  when: ansible_os_family == "Debian"

- name: Add slack dnf repository
  yum_repository:
    name: Slack
    description: Slack DNF repo
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
    gpgcheck: yes
    gpgkey: https://slack.com/gpg/slack_pubkey_20220708.gpg
    enabled: yes
  become: true
  when: ansible_os_family == "RedHat"

- name: install Slack from DNF repo
  yum:
    name: slack
  become: true
  when: ansible_os_family == "RedHat"

- name: create autostart directory
  file:
    path: ~/.config/autostart
    mode: '0775'
    state: directory

- name: start Slack on login
  copy:
    src: files/slack.desktop
    dest: ~/.config/autostart/slack.desktop
