Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.synced_folder "~/git/personal/ansible/xthorsworld", "/opt/source"    
  config.vm.provision "shell", inline: <<-EOF
    # Disable IPv6
    echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
    /sbin/sysctl -p

    # Install EPEL repo
    yum -y install epel-release yum-utils

    # ansible
    yum -y install ansible
   
  EOF
      
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
  end

end
