Vagrant.configure("2") do |config|
  config.vm.box = "becorecode/alpinelinux-3.11"
  config.ssh.shell = "ash"
  # point this at your Ansible source tree
  config.vm.synced_folder "~/git/personal/ansible/xthorsworld", "/opt/source"
  # eventually I'll use config.vm.provision ansible_local, but for now...
  config.vm.provision "shell", inline: <<-EOF
    apk add ansible
  EOF
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1"]
  end
end
