---
- name: Check if Telegram binary is already installed?
  stat:
    path: ~/.local/Telegram/Telegram
  register: telegram_exists

- name: Create Telegram directory in ~/.local
  file:
    path: ~/.local/Telegram
    state: directory
    mode: '0750'

- name: Download and install Telegram
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: ~/.local
    remote_src: True

- name: start Telegram on login
  copy:
    src: files/telegram.desktop
    dest: ~/.config/autostart/telegram.desktop
