---
- name: add apt repositoriy for atareao telegram
  apt_repository:
    repo: ppa:atareao/telegram
    state: present
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: install telegram package
  package:
    name: telegram
    state: present
  become: true