---
- name: add apt key for atareao telegram PPA
  ansible.builtin.get_url:
    url: "http://ppa.launchpad.net/atareao/telegram/ubuntu/dists/{{ ansible_distribution_release }}/Release.gpg"
    dest: /etc/apt/trusted.gpg.d/atareao-telegram-ppa.asc
  when: "'Ubuntu' in ansible_distribution"
  become: true

- name: add apt repositoriy for atareao telegram
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/atareao-telegram-ppa.asc] http://ppa.launchpad.net/atareao/telegram/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: install telegram package
  package:
    name: telegram
    state: present
  become: true