---
- name: add apt key for atareao telegram PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: add apt repositoriy for atareao telegram
  apt_repository:
    repo: "deb http://ppa.launchpad.net/atareao/telegram/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: install telegram package
  package:
    name: telegram
    state: present
  become: true