---
- name: Enable Negativo17.org DNF repo (Fedora)
  command:
    cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
    creates: /etc/yum.repos.d/fedora-spotify.repo
  become: true
