---
# Debian/Ubuntu
- name: add apt keys for spotify
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: add apt repository for spotify
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true 
  when: ansible_os_family == "Debian"

- name: Enable Negativo17.org DNF repo (Fedora)
  command:
      cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
      creates: /etc/yum.repos.d/fedora-spotify.repo
  become: true
  when: "'Fedora' in ansible_distribution"

- name: Enable Negativo17.org DNF repo (Rocky Linux)
  command:
      cmd: dnf config-manager --add-repo=https://negativo17.org/repos/epel-spotify.repo
      creates: /etc/yum.repos.d/epel-spotify.repo
  become: true
  when: "'Rocky' in ansible_distribution"

- name: install spotify package
  package:
    name: spotify-client
    state: present
  become: true
