---
- name: Include Debian tasks
  include_tasks: Debian.yml
  when: "'Debian' in ansible_distribution"

- name: Include Fedora tasks
  include_tasks: Fedora.yml
  when: "'Fedora' in ansible_distribution"

- name: install spotify package
  package:
    name: spotify-client
    state: present
  become: true
