---
- name: Enable Negativo17.org DNF repo (Rocky Linux)
  command:
    cmd: dnf config-manager --add-repo=https://negativo17.org/repos/epel-spotify.repo
    creates: /etc/yum.repos.d/epel-spotify.repo
  become: true
