---
- name: Install pushover_me.sh script in /usr/local/bin
  ansible.builtin.template:
    src: templates/pushover_me.sh
    dest: /usr/local/bin/pushover_me.sh
    owner: root
    group: root
    mode: '0755'
