---
- name: create ~/.local/bin directory
  file:
    path: ~/.local/bin
    mode: 0770
    recurse: yes

- name: Create ~/Downloads directory
  file:
    path: ~/Downloads
    state: directory
    mode: '0750'
