---
- name: add gpg yum keys for 1password
  rpm_key:
    key: "https://downloads.1password.com/linux/keys/1password.asc"
    state: present
  become: true
  when: "'Fedora' in ansible_distribution"

- name: Add 1password yum repository
  yum_repository:
    name: 1password
    description: 1password repo
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch/
    gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    enabled: yes
  become: true
  when: "'Fedora' in ansible_distribution"

- name: import GPG key for 1password to filesystem
  shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/1password-archive-keyring.gpg
  when: ansible_os_family == "Debian"

- name: add apt keys for 1password
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  become: true
  when: ansible_os_family == "Debian"

- name: add apt repository for 1password
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install 1password package
  package:
    name: 1password
    state: present
  become: true
