---
- name: add gpg yum keys for 1password
  rpm_key:
    key: "https://downloads.1password.com/linux/keys/1password.asc"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: install 1password RPM
  yum:
    name: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
  become: true 
  when: ansible_os_family == "RedHat"

- name: install 1password DEB
  apt:
    deb: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"
  become: true 
  when: ansible_os_family == "Debian"

- name: install 1password-cli
  yum:
    name: 1password-cli
  become: true 
  when: ansible_os_family == "RedHat"