---
- name: add gpg yum keys for 1password
  rpm_key:
    key: "https://downloads.1password.com/linux/keys/1password.asc"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Check if /opt/1Password/1password exists
  stat:
    path: /opt/1Password/1password
  register: stat_1pbin_file

- name: install 1password RPM
  yum:
    name: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
  become: true 
  when: ansible_os_family == "RedHat" and not stat_1pbin_file.stat.exists

- name: install 1password DEB
  apt:
    deb: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"
  become: true 
  when: ansible_os_family == "Debian" and not stat_1pbin_file.stat.exists

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  become: true

- name: install 1password-cli
  package:
    name: 1password-cli
  become: true
