---
- name: add gpg yum keys for 1password
  rpm_key:
    key: "https://downloads.1password.com/linux/keys/1password.asc"
    state: present
  when: "'Fedora' in ansible_distribution"

- name: Add 1password yum repository
  yum_repository:
    name: 1password
    description: 1password repo
    baseurl: https://downloads.1password.com/linux/rpm
    gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    enabled: yes
  become: true
  when: "'Fedora' in ansible_distribution"

- name: add apt keys for 1password
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  become: true
  when: "'Ubuntu' in ansible_distribution"

- name: add apt repository for 1password
  apt_repository:
    repo: "deb [arch=amd64] https://downloads.1password.com/linux/debian edge main"
    state: present
  become: true
  when: "'Ubuntu' in ansible_distribution"

- name: install 1password package
  package:
    name: 1password
    state: present
  become: true
