---
- name: include local-dirs role
  include_role:
    name: local-dirs

- name: Download awscliv2 installer
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "~/tmp"
    remote_src: true
    creates: '~/tmp/aws'
    mode: 0755

- name: Run the installer
  command:
  args:
    cmd: "~/tmp/aws/install -i ~/.local/aws-cli -b ~/.local/bin"
    creates: "~/.local/bin/aws"
  register: aws_install

- name: "Show installer output"
  debug:
    var: aws_install
    verbosity: 2