---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: true

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Check if .oh-my-zsh/custom/themes/powerlevel10k exists
  stat:
    path: ~/.oh-my-zsh/custom/themes/powerlevel10k
  register: stat_zsh_theme_result

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1
  when: not stat_oh_my_zsh_result.stat.exists

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1
  when: not stat_oh_my_zsh_result.stat.exists

- name: Cloning powerlevel10k repo
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
  when: not stat_zsh_theme_result.stat.exists

- name: Creating new ~/.zshrc
  copy:
    src: templates/zshrc.j2
    dest: ~/.zshrc
  when: not stat_rc_result.stat.exists

- name: Create fonts directory
  file:
    path: ~/.fonts
    state: directory
    mode: '0750'

- name: install font MesloLGS Regular
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: ~/.fonts/MesloLGS_NF_Regular.ttf
    mode: '0640'

- name: install font MesloLGS Bold
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: ~/.fonts/MesloLGS_NF_Bold.ttf
    mode: '0640'
  notify: refresh font cache

- name: install font MesloLGS Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: ~/.fonts/MesloLGS_NF_Italic.ttf
    mode: '0640'
  notify: refresh font cache

- name: install font MesloLGS Italic
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: ~/.fonts/MesloLGS_NF_Bold_Italic.ttf
    mode: '0640'
  notify: refresh font cache

- name: change user shell to zsh
  command: chsh -s /bin/zsh "{{ lookup('env', 'USER') }}"
  become: true