- name: install packages for libvirt
  dnf:
    name:
      - cloud-utils
      - qemu-kvm
      - libvirt
      - bridge-utils
      - virt-install
      - virt-manager
      - libguestfs-tools
      - virt-top
    state: present
    update_cache: yes
  become: true
