---
- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Debian tasks
  include_tasks: Debian.yml
  when: "'Debian' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Pop!_OS' in ansible_distribution"

- name: Include Linux Mint (just Ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Linux Mint' in ansible_distribution"

- name: Include Fedora tasks
  include_tasks: Fedora.yml
  when: "'Fedora' in ansible_distribution"

- name: start libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes
  become: true

- name: Add my account to libvirt group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
    append: yes
  become: true
