---
- name: Set fact - OS-specific packages
  set_fact:
    os_packages: "{{ lookup('vars', ansible_os_family + '_packages') }}"

- name: Install common libvirt packages
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages }}"
  when: "ansible_distribution == 'Fedora'"

- name: Install OS-specific libvirt packages
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ os_packages }}"
  when: "ansible_distribution == 'Fedora'"

- name: Install common libvirt packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages }}"
  when: ansible_os_family == "Debian"

- name: Install OS-specific libvirt packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ os_packages }}"
  when: ansible_os_family == "Debian"

- name: start libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes
  become: true

- name: Add my account to libvirt group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
    append: yes
  become: true
