---
- name: Set fact - OS-specific packages
  set_fact:
    os_packages: "{{ lookup('vars', ansible_os_family + '_packages') }}"

- name: Install common libvirt packages - RHEL family
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages_libvirt }}"
  when: ansible_os_family == "RedHat"

- name: Install OS-specific libvirt packages - RHEL family
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ RedHat_packages_libvirt }}"
  when: ansible_os_family == "RedHat"

- name: Install common libvirt packages - Debian family
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages_libvirt }}"
  when: ansible_os_family == "Debian"

- name: Install OS-specific libvirt packages - Debian family
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ debian_packages_libvirt }}"
  when: ansible_os_family == "Debian"

- name: start libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes
  become: true

- name: Add my account to libvirt group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
    append: yes
  become: true
