---
- name: Include Debian tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Pop!_OS' in ansible_distribution"

- name: Include Fedora tasks
  include_tasks: Fedora.yml
  when: "'Fedora' in ansible_distribution"
