zabbix_agent_dont_detect_ip: true
zabbix_agent_become_on_localhost: false
zabbix_install_pip_packages: false
zabbix_api_server_url: http://zabbixt1.xthorsworld.lab
zabbix_api_use: true
zabbix_api_login_user: Admin
zabbix_api_login_pass: zabbix
zabbix_agent_host_state: present
zabbix_host_groups:
  - Linux Servers
zabbix_agent_link_templates:
  - Template OS Linux