---
- name: Install sudo
  apt:
    name: sudo
    state: present
  become: true

- name: Add xthor user
  ansible.builtin.user:
    name: xthor
    shell: /bin/bash
    append: yes
  become: true

- name: sudo without password for xthor
  copy:
    content: 'xthor ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/xthor_nopasswd
    validate: 'visudo -cf %s'
    mode: 0440
