---
- name: Install sudo
  apt:
    name: sudo
    state: present
  become: true

- name: Add xthor user
  ansible.builtin.user:
    name: xthor
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'