---
- name: install Conky - Fedora
  become: true
  package:
    name:
      - conky
      - redhat-lsb-core # for lsb_release command
  when: "'Fedora' in ansible_distribution"

- name: install Conky - Ubuntu
  become: true
  package:
    name:
      - conky-all
  when: ansible_os_family == "Debian"

- name: create autostart config dir
  file:
    path: ~/.config/autostart
    state: directory
    mode: '0750'

- name: get active network interface information
  set_fact:
    interface_module: "{{ vars['ansible_'~ansible_default_ipv4.alias].module }}"

- name: template conkyrc file
  template:
    src: templates/conkyrc
    dest: ~/.conkyrc
    mode: '0660'
    force: no

- name: copy conkyrc autostart file
  copy:
    src: files/conky.desktop
    dest: ~/.config/autostart/conky.desktop
    mode: '0660'