---
- name: set fact for desktop environment
  set_fact:
    desktop_env: "{{ lookup('env', 'DESKTOP_SESSION' ) | ternary (lookup('env', 'DESKTOP_SESSION' ), omit) }}"

- name: Apply GNOME settings (Ubuntu)
  include_role:
    name: gnome-settings
  when: desktop_env == "ubuntu"

- name: Apply GNOME settings (Pop OS)
  include_role:
    name: gnome-settings
  when: desktop_env == "pop"

- name: Apply XFCE settings
  include_role:
    name: xfce-settings
  when: desktop_env == "xubuntu"

- name: Apply GNOME settings
  include_role:
    name: gnome-settings
  when: desktop_env == "gnome"

- name: Apply Cinnamon settings
  include_role:
    name: cinnamon-settings
  when: desktop_env == "cinnamon"

- name: Apply XFCE settings
  include_role:
    name: xfce-settings
  when: desktop_env == "xfce"

- name: Apply Openbox settings
  include_role:
    name: openbox
  when: desktop_env == "openbox"

- name: Apply Budgie settings
  include_role:
    name: budgie-settings
  when: desktop_env == "budgie-desktop"
