---
- name: install required gnome packages - Debian Family
  become: true
  apt:
    name:
      - python3-psutil
      - dconf-cli
      - gnome-tweaks
      - gnome-shell-extensions
      - arc-theme
      - numix-icon-theme
      - chrome-gnome-shell
      - breeze-icon-theme
  when: ansible_os_family == "Debian"

- name: install required gnome packages - RedHat Family
  become: true
  package:
    name:
      - python3-psutil
      - gnome-tweaks
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-common
      - chrome-gnome-shell
      - arc-theme
      - numix-icon-theme
      - breeze-icon-theme
      - gnome-extensions-app
  when: ansible_os_family == "RedHat"

# looks like horizontal workspaces is back in F34, so...
- name: install required gnome packages - Fedora 33 only
  become: true
  package:
    name:
      - gnome-shell-extension-horizontal-workspaces
  when: "ansible_distribution == 'Fedora' and ansible_distribution_version == '33'"

# gnome interface settings

- name: prefer dark color scheme (new in GNOME 40)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

# I removed this - but it turns out, without it set, older apps don't get the right theme :manshrug:
- name: gtk theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"

- name: clock show date
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: clock format
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

- name: icon theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'breeze-dark'"

- name: full LCD hinting
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-hinting"
    value: "'full'"

- name: rgba anti-aliasing
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-antialiasing"
    value: "'rgba'"

- name: enable gnome extensions
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"
  when: "ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora'"

- name: disable ubuntu dock
  community.general.dconf:
    key: "/org/gnome/shell/disabled-extensions"
    value: "['ubuntu-dock@ubuntu.com']"
  when: "ansible_distribution == 'Ubuntu'"

#- name: set user theme to Arc-Dark
#  dconf:
#    key: "/org/gnome/shell/extensions/user-theme/name"
#    value: "'Arc-Dark'"

# mutter settings

- name: workspaces span displays
  community.general.dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"

# power settings

- name: show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: blank screen after 15 minutes
  community.general.dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 900"

- name: sleep when inactive for 15 minutes
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "'nothing'"

# terminal settings

- name: terminal transparency enabled
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
    value: "true"

- name: terminal background transparency percent
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "13"

- name: terminal default rows
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows"
    value: "30"

- name: terminal unlimited scrollback
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollback-unlimited"
    value: "true"

- name: terminal disable scrollbar
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy"
    value: "'never'"

- name: terminal disable using system font
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
    value: "false"

- name: terminal disable using theme colors
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "false"

- name: terminal disable using theme transparency
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency"
    value: "false"

- name: terminal foreground color
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(255,255,255)'"

- name: terminal background color
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(0,0,0)'"

- name: terminal color palette
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette"
    value: "['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(0,0,205)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(250,235,215)', 'rgb(64,64,64)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(0,0,255)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']"

# these get in the way of terminator's hotkeys
- name: ibus disable hotkey
  community.general.dconf:
    key: "/desktop/ibus/panel/emoji/hotkey"
    value: "@as []"

- name: ibus disable unicode hotkey
  community.general.dconf:
    key: "/desktop/ibus/panel/emoji/unicode-hotkey"
    value: "@as []"

# touchpad settings

- name: disable touchpad natural scrolling
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"

- name: disable touchpad tap-to-click
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "false"

- name: two-finger right-click (instead of corner)
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/click-method"
    value: "'fingers'"

# gedit

- name: set gedit theme to solarized dark
  community.general.dconf:
    key: "/org/gnome/gedit/preferences/editor/scheme"
    value: "'solarized-dark'"

# keybindings

- name: set keybindings for moving between workspaces - down
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
    value: "['<Primary><Shift><Super>Down', '<Primary><Shift><Alt>Down']"
  when: "ansible_distribution == 'Pop!_OS'"

- name: set keybindings for moving between workspaces - up
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
    value: "['<Primary><Shift><Super>Up', '<Primary><Shift><Alt>Up']"
  when: "ansible_distribution == 'Pop!_OS'"

- name: set keybindings for moving windows between workspaces - up
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-up"
    value: "['<Primary><Super>Up', '<Primary><Super>KP_Up', '<Primary><Super>k', '<Primary><Alt>Up']"
  when: "ansible_distribution == 'Pop!_OS'"

- name: set keybindings for moving windows between workspaces - down
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down"
    value: "['<Primary><Super>Down', '<Primary><Super>KP_Down', '<Primary><Super>j', '<Primary><Alt>Down']"
  when: "ansible_distribution == 'Pop!_OS'"

# I'd like to set the background, but I'm gonna need to do some fancy-shmancy sed shit to make this work
# xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/'
# then copy in the right file (4k or 1080p) and set it
# dconf: "org/gnome/desktop/background/picture-uri"
# value: 'file:///home/xthor/Pictures/...'
