- name: install playbook requirements
  become: true
  package:
    name:
      - python-psutil
      - dconf-cli
      - gnome-tweaks
      - gnome-shell-extensions

- name: show battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: clock show date
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"