---
- name: Add vscode yum repository
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: yes
  become: true
  when: ansible_os_family == "RedHat"

- name: add yum GPG key for vscode
  rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: true 
  when: ansible_os_family == "RedHat"

- name: install vscode package
  package:
    name: code
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: install deb package for vscode from https
  apt:
    deb: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
  become: true
  when: "'Debian' in ansible_os_family"

#- name: add apt key for vscode repo
#  ansible.builtin.get_url:
#    url: "https://packages.microsoft.com/repos/vscode/dists/stable/Release.gpg"
#    dest: /etc/apt/trusted.gpg.d/vscode.asc
#  become: true
#  when: "'Debian' in ansible_os_family"

#- name: add apt repositoriy for vscode
#  apt_repository:
#    repo: "deb [arch=amd64,signed-by=/etc/apt/trusted.gpg.d/vscode.asc] https://packages.microsoft.com/repos/vscode stable main"
#    state: present
#  become: true 
#  when: "'Debian' in ansible_os_family"
