---
- name: install tools
  apt: name={{item}} state=present
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present

- name: configure nginx sites
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active
  changed_when: "active.stdout_lines != sites.keys() | list"

# an example of how to spit out a variable if you're debugging Ansible stuff
- debug: var=active.stdout_lines
# Below is an example of how to output *ALL* variables
- debug: var=vars
  
- name: de-activate sites
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: "{{ active.stdout_lines }}"
  when: item not in "{{ sites }}"

- name: kill default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: enable nginx sites
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: start nginx
  service: name=nginx state=started enabled=yes
