- name: install OSCAR deb for Ubuntu 22.04 and families
  apt:
    deb: "https://www.apneaboard.com/OSCAR/oscar_1.4.0-Ubuntu22_amd64.deb"
  become: true 
  when: "ansible_os_family == 'Debian' ansible_distribution_major_version == '22.04'"
