- name: Enable Fedora Copr for Autorandr
  command:
      cmd: dnf copr enable -y tofik/autorandr 
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:tofik:autorandr.repo
  become: true

- name: install packages for Openbox
  dnf:
    name:
      - lxqt-openssh-askpass
      - firefox
      - blueman
      - arc-theme
      - tint2
      - openbox
      - obconf
      - compton
      - volumeicon
      - nitrogen
      - conky
      - arandr
      - mousepad
      - lxappearance
      - lxterminal
      - xbacklight
      - flameshot
      - playerctl
      - mate-calc
      - lxdm
      - xfce4-appfinder
      - mupdf
      - numix-icon-theme
      - thunar
      - dunst
      - autorandr
      - xautolock
      - maim
      - i3lock
      - ImageMagick
      - liberation-fonts
      - pavucontrol
    state: present
    update_cache: yes
  become: true

- name: remove unnecessary packages that come with Fedora's LXDE spin
  dnf:
    name:
      - pcmanfm
      - xscreensaver-base
    state: absent
  become: true