# add GPG keys for repositories
- name: add yum gpg keys from urls
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://download.opensuse.org/repositories/home:/phillipberndt/Fedora_{{ ansible_distribution_version }}/repodata/repomd.xml.key" # autorandr
  become: true 

# add yum repositories
# didn't use yum_repository here because this file has a line in it I can't manage in
- name: template yum repo file for autorandr
  become: true
  template:
    src: templates/autorandr.repo.j2
    dest: /etc/yum.repos.d/autorandr.repo
    mode: '0664'
    owner: root
    group: root

- name: install packages for Openbox
  dnf:
    name:
      - lxqt-openssh-askpass
      - firefox
      - blueman
      - arc-theme
      - tint2
      - openbox
      - obconf
      - compton
      - volumeicon
      - nitrogen
      - conky
      - arandr
      - mousepad
      - lxappearance
      - lxterminal
      - xbacklight
      - flameshot
      - playerctl
      - mate-calc
      - lxdm
      - xfce4-appfinder
      - mupdf
      - numix-icon-theme
      - thunar
      - dunst
      - autorandr
      - xautolock
      - maim
      - i3lock
      - ImageMagick
      - liberation-fonts
      - pavucontrol
    state: present
    update_cache: yes
  become: true