---
- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Pop!_OS' in ansible_distribution"

- name: template conkyrc file
  template:
    src: templates/conkyrc.j2
    dest: ~/.conkyrc
    mode: '0660'

- name: template compton conf file
  template:
    src: templates/conkyrc.j2
    dest: ~/.config/compton.conf
    mode: '0660'

- name: create config dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items:
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml
    - ~/.config/tint2
    - ~/.config/terminator
    - ~/.config/volumeicon
    - ~/.config/openbox
    - ~/.config/gtk-3.0

- name: copy tint2 config file
  copy:
    src: files/tint2rc
    dest: ~/.config/tint2/tint2rc
    mode: '0660'

- name: copy xfce4-power-manager config file
  copy:
    src: files/xfce4-power-manager.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    mode: '0660'

- name: copy volumeicon config file
  copy:
    src: files/volumeicon
    dest: ~/.config/volumeicon/volumeicon
    mode: '0660'

- name: copy openbox autostart config file
  copy:
    src: files/autostart
    dest: ~/.config/openbox/autostart
    mode: '0770'

- name: copy openbox rc.xml config file
  copy:
    src: files/rc.xml
    dest: ~/.config/openbox/rc.xml
    mode: '0660'

- name: copy terminator config file
  copy:
    src: files/terminator-config
    dest: ~/.config/terminator/config
    mode: '0660'

- name: copy gtk-3.0 config file
  copy:
    src: files/gtk30settings.ini
    dest: ~/.config/gtk-3.0/settings.ini
    mode: '0660'

- name: install i3lock-fancy-rapid binary
  copy: 
    src: files/bin/i3lock-fancy-rapid
    dest: ~/bin/i3lock-fancy-rapid
    mode: '0770'

- name: install dock.sh script
  copy: 
    src: files/bin/dock.sh
    dest: ~/bin/dock.sh
    mode: '0770'

- name: install undock.sh script
  copy: 
    src: files/bin/undock.sh
    dest: ~/bin/undock.sh
    mode: '0770'

- name: install lockscreen.sh binary
  copy: 
    src: files/bin/lockscreen.sh
    dest: ~/bin/lockscreen.sh
    mode: '0770'

# TODO: need to set lightdm as default DE, and set a nice theme there, that's dark