---
- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Pop!_OS' in ansible_distribution"

- name: Include Fedora tasks
  include_tasks: Fedora.yml
  when: "'Fedora' in ansible_distribution"
  
- name: create config dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items:
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml
    - ~/.config/tint2
    - ~/.config/terminator
    - ~/.config/volumeicon
    - ~/.config/openbox
    - ~/.config/gtk-3.0
    - ~/bin
    - ~/.screenlocker

- name: template conkyrc file
  copy:
    src: files/conkyrc
    dest: ~/.conkyrc
    mode: '0660'
    force: no

- name: template compton conf file
  copy:
    src: files/compton.conf
    dest: ~/.config/compton.conf
    mode: '0660'
    force: no

- name: copy tint2 config file
  copy:
    src: files/tint2rc
    dest: ~/.config/tint2/tint2rc
    mode: '0660'
    force: no

- name: copy xfce4-power-manager config file
  copy:
    src: files/xfce4-power-manager.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    mode: '0660'
    force: no

- name: copy volumeicon config file
  copy:
    src: files/volumeicon
    dest: ~/.config/volumeicon/volumeicon
    mode: '0660'
    force: no

- name: copy openbox autostart config file
  copy:
    src: files/autostart
    dest: ~/.config/openbox/autostart
    mode: '0770'
    force: no

- name: copy openbox rc.xml config file
  copy:
    src: files/rc.xml
    dest: ~/.config/openbox/rc.xml
    mode: '0660'
    force: no

- name: copy terminator config file
  copy:
    src: files/terminator-config
    dest: ~/.config/terminator/config
    mode: '0660'
    force: no

- name: copy gtk-3.0 config file
  copy:
    src: files/gtk30settings.ini
    dest: ~/.config/gtk-3.0/settings.ini
    mode: '0660'
    force: no

- name: copy lockscreen script to ~/bin
  copy:
    src: files/lockscreen.sh
    dest: ~/bin/lockscreen.sh
    mode: '0750'

- name: copy screenlocker script to ~/.screenlocker
  copy:
    src: files/lock
    dest: ~/.screenlocker/lock
    mode: '0770'

- name: copy lock png to ~/.screenlocker
  copy:
    src: files/lock.png
    dest: ~/.screenlocker/lock.png
    mode: '0660'

- name: copy text png to ~/.screenlocker
  copy:
    src: files/text.png
    dest: ~/.screenlocker/text.png
    mode: '0660'

- name: checkout oblogout-py3 repo
  ansible.builtin.git:
    repo: 'https://github.com/trizen/oblogout-py3.git'
    dest: ~/git/github/oblogout-py3

- name: Copy the themes from oblogout-py3 to themes dir
  copy:
    src: ~/git/github/oblogout-py3/data/themes
    dest: ~/.themes
    directory_mode: yes

- name: install oblogout-py3
  shell: ./setup.py install
  chdir: ~/git/github/oblogout-py3
  creates: /etc/oblogout.conf
  become: true

# TODO: need to set lxdm as default DE, and set a nice theme there, that's dark