# add GPG keys for repositories
- name: add apt keys from urls
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.opensuse.org/repositories/home:/phillipberndt/xUbuntu_{{ ansible_distribution_version }}/Release.key" # autorandr
  become: true 

# add apt repositories
- name: add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://download.opensuse.org/repositories/home:/phillipberndt/xUbuntu_{{ ansible_distribution_version }}/ /"
  become: true 

- name: install packages for Openbox
  apt:
    name:
      - lxqt-openssh-askpass
      - firefox
      - blueman
      - arc-theme
      - tint2
      - ssh-askpass
      - openbox
      - obconf
      - compton
      - volumeicon-alsa
      - nitrogen
      - conky-all
      - arandr
      - mousepad
      - lxappearance
      - lxterminal
      - nm-tray
      - xbacklight
      - flameshot
      - playerctl
      - mate-calc
      - lightdm-gtk-greeter
      - xfce4-appfinder
      - mupdf
      - numix-icon-theme
      - thunar
      - dunst
      - autorandr
      - xautolock
      - scrot
      - i3lock
      - imagemagick
      - git # probably already here, but just in case...
    state: present
    update_cache: yes
  become: true