- name: install packages for Openbox
  apt:
    name:
      - lxqt-openssh-askpass
      - blueman
      - arc-theme
      - tint2
      - xfce4-notifyd
      - ssh-askpass
      - openbox
      - obconf
      - compton
      - volumeicon-alsa
      - nitrogen
      - conky-all
      - arandr
      - mousepad
      - lxappearance
      - nm-tray
      - xbacklight
      - flameshot
      - playerctl
      - mate-calc
      - lightdm-gtk
      - xfce4-appfinder
      - xss-lock
      - i3lock
      - mupdf
      - numix-icon-theme
      - thunar
      - dunst
    state: present
    update_cache: yes
  become: true
