# this is exactly the same as Ubuntu, from a package perspective. But I decided I wanted to leave them separate.
- name: install necessary packages
  apt:
    name:
      - curl
      - awscli
      - nmap
      - zsh
      - ncdu
      - pwgen
      - htop
      - putty-tools
      - axel
      - freerdp2-x11
      - mpv
      - network-manager-openvpn-gnome
      - f3
      - screen
      - p7zip-full
      - iperf3
      - xorriso
      - jq
      - golang
      - python3-boto
      - python3-pip
      - whois
      - flatpak
      - sysstat
      - smartmontools
    state: present
    update_cache: yes
  become: true 

# full upgrade, just to be safe, some of the above packages will add apt sources and this will upgrade them
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true 

