- name: add yum GPG keys for rpmfusion
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020" # rpmfusion free
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020" # rpmfusion non-free
  become: true 

- name: install the rpmfusion repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  become: true

- name: install necessary packages
  dnf:
    name:
      - curl
      - awscli
      - nmap
      - zsh
      - ncdu
      - pwgen
      - htop
      - putty
      - axel
      - mpv
      - NetworkManager-openvpn-gnome
      - f3
      - screen
      - p7zip-plugins
      - iperf3
      - xorriso
      - jq
      - golang
      - python3-boto
      - python3-pip
      - whois
      - flatpak
      - transmission-gtk
      - calibre
      - sysstat
      - smartmontools
    state: present
    update_cache: yes
  become: true 

# full upgrade, just to be safe, some of the above packages will add apt sources and this will upgrade them
- name: Update all packages to their latest version
  dnf:
    name: "*"
    state: latest
  become: true 
