---
- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  become: true
  when: "'Pop!_OS' in ansible_distribution"

- name: create bin directory in users home dir
  file:
    path: ~/bin
    state: directory
    mode: '0750'

# TODO: put in a check so the zip doesn't download if the vault binary exists
# at least, I think, it's downloading the zip even if we don't need it.
- name: Install Telegram Desktop client
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: ~/bin
    remote_src: yes

- name: Install pCloud client
  get_url:
    url: https://www.pcloud.com/how-to-install-pcloud-drive-linux.html?download=electron-64
    dest: ~/bin/pcloud
    mode: '0750'

# TODO:

# store SSH key in ansible-vault? Or use 1password CLI to extract it? That's an interesting idea...

# plus I should really template out my dotfiles and store them here
# - for openbox, but also vim and stuffs. and ~/tmp, because vim uses that