---
- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution"
  
- name: Include Pop!_OS tasks (really, just ubuntu)
  include_tasks: Ubuntu.yml
  when: "'Pop!_OS' in ansible_distribution"

- name: create bin directory in users home dir
  file:
    path: ~/bin
    state: directory
    mode: '0750'

- name: Open download link for pCloud in a browser window
  shell: xdg-open https://www.pcloud.com/how-to-install-pcloud-drive-linux.html?download=electron-64

# TODO:

# store SSH key in ansible-vault? Or use 1password CLI to extract it? That's an interesting idea...

# plus I should really template out my dotfiles and store them here
# - for openbox, but also vim and stuffs. and ~/tmp, because vim uses that