# add GPG keys for repositories
- name: kubectl, vscode, and pgadmin4 apt key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://packages.microsoft.com/keys/microsoft.asc"
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

- name: add apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 3FEF9748469ADBE15DA7CA80AC2D62742012EA22 # 1password

# add apt repositories
- name: add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://repo.pritunl.com/stable/apt {{ ansible_distribution_release }} main"
    - "deb [arch=amd64] https://downloads.1password.com/linux/debian edge main"

- name: install deb packages from URLs
  apt:
    deb: "{{ item }}"
  with_items:
    - "https://prerelease.keybase.io/keybase_amd64.deb"
    - "https://zoom.us/client/latest/zoom_amd64.deb"
    - "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.13.0-amd64.deb"

# install apps with apt
- name: install Ubuntu packages for DevOps workstation
  apt:
    name:
      - kubectl
      - vim
      - vim-gtk3
      - code
      - ansible
      - awscli
      - nmap
      - zsh
      - 1password
      - terminator
      - ncdu
      - pwgen
      - htop
      - putty-tools
      - conky-all
      - axel
      - remmina-plugin-rdp
      - freerdp2-x11
      - mpv
      - network-manager-openvpn-gnome
    state: present
    update_cache: yes

# full upgrade, just to be safe, some of the above packages will add apt sources and this will upgrade them
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

# install packages from snap
- name: Install packages from snap
  snap:
    name:
      - simplenote
      - spotify
      - standard-notes
      - todoist
