# TODO: remove everything in this task EXCEPT what comes with the OS!
# make the list of apps a default instead of a built-in list, and put it in the main.yml so it can be called with package instead
- name: install necessary packages
  apt:
    name:
      - curl
      - awscli
      - nmap
      - zsh
      - ncdu
      - pwgen
      - htop
      - putty-tools
      - axel
      - remmina-plugin-rdp
      - freerdp2-x11
      - mpv
      - network-manager-openvpn-gnome
      - f3
      - screen
      - p7zip-full
      - iperf3
      - podman
      - xorriso
      - jq
      - golang
      - python3-boto
      - python3-pip
      - whois
      - flatpak
      - sysstat
      - smartmontools
    state: present
    update_cache: yes
  become: true 

# full upgrade, just to be safe, some of the above packages will add apt sources and this will upgrade them
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true 

- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes
  become: true

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
  become: true