# add GPG keys for repositories
- name: add apt keys from urls
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://packages.microsoft.com/keys/microsoft.asc" # vscode
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg" # kubectl
    - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key" # podman
  become: true 

- name: add apt keys from ubuntu keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 3FEF9748469ADBE15DA7CA80AC2D62742012EA22 # 1password
  become: true 

# add apt repositories
- name: add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb [arch=amd64] https://downloads.1password.com/linux/debian edge main"
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
  become: true 

- name: install deb packages from URLs
  apt:
    deb: "{{ item }}"
  with_items:
    - "https://prerelease.keybase.io/keybase_amd64.deb"
    - "https://zoom.us/client/latest/zoom_amd64.deb"
    - "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.13.0-amd64.deb"
  become: true 

# install apps with apt
- name: install necessary packages
  apt:
    name:
      - curl
      - kubectl
      - vim
      - vim-gtk3
      - code
      - ansible
      - awscli
      - nmap
      - zsh
      - 1password
      - ncdu
      - pwgen
      - htop
      - putty-tools
      - axel
      - remmina-plugin-rdp # todo: move this to flatpak
      - freerdp2-x11
      - mpv
      - network-manager-openvpn-gnome
      - f3
      - screen
      - p7zip-full
      - iperf3
      - podman
      - xorriso
      - jq
      - golang
      - python3-boto
      - python3-pip
      - whois
      - flatpak
    state: present
    update_cache: yes
  become: true 

# full upgrade, just to be safe, some of the above packages will add apt sources and this will upgrade them
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true 

- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd

- name: Install apps from flatpak
  community.general.flatpak:
    name: 
      - com.spotify.Client
      - com.simplenote.Simplenote
      - com.todoist.Todoist
      - org.telegram
    state: present
    method: user

# install packages from snap
- name: Install packages from snap
  snap:
    name:
      - simplenote
      - spotify
      - standard-notes
      - todoist
      - telegram-desktop
  become: true 
