---
- name: install deb-multimedia-keyring for deb-multimedia repo
  apt:
    deb: http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: add deb-multimedia repo to Debian system
  apt_repository:
    repo: "deb https://www.deb-multimedia.org {{ ansible_distribution_release }} main non-free"
    state: present
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: Update all packages to their latest version (for deb-multimedia)
  apt:
    name: "*"
    state: latest
  become: true

- name: install packages to manage media
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xfsprogs
    - openjdk-11-jdk-headless
    - jq
    - bc
    - curl
    - screen
    - xrdp
    - htop
    - mediainfo
    - mediainfo-gui
    - mkvtoolnix
    - mkvtoolnix-gui
    - inotify-tools
  become: true

- name: make a dir for handbrake presets
  file:
    path: ~/.handbrake-presets
    state: directory
    mode: '0750'

- name: install handbrake presets
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0660'
  with_items:
    - { src: 'files/1080p_qsv.json', dest: '~/.handbrake-presets/1080p_qsv.json' }
    - { src: 'files/4k_qsv.json', dest: '~/.handbrake-presets/4k_qsv.json' }

- name: install ripper scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0770'
    owner: "{{ ansible_user_id }}"
  with_items:
    - { src: 'files/batch_encode.sh', dest: '/usr/local/bin/batch_encode.sh' }
    - { src: 'files/ripdisc.sh', dest: '/usr/local/bin/ripdisc.sh' }
    - { src: 'files/encode_file.sh', dest: '/usr/local/bin/encode_file.sh' }
    - { src: 'files/watch_encode_dir.sh', dest: '/usr/local/bin/watch_encode_dir.sh' }
    - { src: 'files/watch_for_disc.sh', dest: '/usr/local/bin/watch_for_disc.sh' }
  become: true
