---
- name: add apt keys for podman
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present
  become: true
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '22'"

- name: add apt repository for podman
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
  become: true 
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '22'"

- name: install podman package
  package:
    name:
      - podman
      - podman-docker
    state: present
  become: true