---
root_password_hash: "{{ lookup('community.general.onepassword', 'root_password_hash', field='password', vault='Ansible') }}"
xthor_password_hash: "{{ lookup('community.general.onepassword', 'xthor_password_hash', field='password', vault='Ansible') }}"