---
- name: Set fact - OS-specific packages
  set_fact:
    os_packages: "{{ lookup('vars', ansible_os_family + '_packages') }}"

# I had to switch from `package` to each respective package manager command. Otherwise, `package` runs the package manager once per item. Yuck.
- name: Install common packages - RHEL family
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages }}"
  when: ansible_os_family == "RedHat"

- name: Install OS-specific packages - RHEL family
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ os_packages }}"
  when: ansible_os_family == "RedHat"

- name: Install common packages - Debian family
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ common_packages }}"
  when: ansible_os_family == "Debian"

- name: Install OS-specific packages - Debian family
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ os_packages }}"
  when: ansible_os_family == "Debian"

