---
- name: Include Fedora tasks
  include_tasks: Fedora.yml
  when: "'Fedora' in ansible_distribution"

- name: Include Ubuntu tasks
  include_tasks: Ubuntu.yml
  when: "'Ubuntu' in ansible_distribution or 'Pop!_OS' in ansible_distribution"

- name: Include Debian tasks
  include_tasks: Debian.yml
  when: "'Debian' in ansible_distribution"
