---
- name: add Google Chrome DNF repo
  yum_repository:
    name: google-chrome
    description: Google Chrome Repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: yes
  become: true
  when: "'Fedora' in ansible_distribution"

- name: add yum GPG key for Google Chrome
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true 
  when: "'Fedora' in ansible_distribution"

# for debian-based distros, all we really need to do is install the deb file. The repo will be added by a script
# that installs with the package.
- name: install Google Chrome DEB
  apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  become: true 
  when: ansible_os_family == "Debian"
