---
- name: add Google Chrome DNF repo
  yum_repository:
    name: google-chrome
    description: Google Chrome Repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: yes
  become: true
  when: "'Fedora' in ansible_distribution"

- name: add yum GPG key for Google Chrome
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true 
  when: "'Fedora' in ansible_distribution"

- name: add apt key for Google Chrome repo
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: add apt repositoriy for vscode
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
  become: true 
  when: "'Ubuntu' in ansible_distribution"

- name: install Google Chrome package
  package:
    name: google-chrome-stable
    state: present
  become: true