---
- name: add apt key for firefox ppa
  ansible.builtin.get_url:
    url: https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/dists/jaunty/Release.gpg
    dest: /etc/apt/trusted.gpg.d/mozilla-firefox-ppa.asc
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'"
  become: true

- name: add apt repositoriy for firefox
  ansible.builtin.apt_repository:
    filename: ppa_mozillateam.list
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/mozilla-firefox-ppa.asc] https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu {{ ansible_distribution_release }} main"
  become: true
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'"

- name: prefer mozillateam PPA in apt preferences
  copy:
    src: files/apt-prefs-mozilla-firefox
    dest: /etc/apt/preferences.d/mozilla-firefox
    mode: '0664'
    owner: root
    group: root
  become: true
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'"

- name: allow firefox updates to be installed automatically from ppa
  copy:
    src: files/unattended-upgrades-firefox
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    mode: '0664'
    owner: root
    group: root
  become: true
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'"

- name: install firefox package
  package:
    name: firefox
    state: present
  become: true
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'"