---
- name: add yum GPG key for keybase
  rpm_key:
    key: "https://keybase.io/docs/server_security/code_signing_key.asc"
    state: present
  become: true 
  when: "'Fedora' in ansible_distribution"

- name: install keybase RPM
    yum:
      name: "https://prerelease.keybase.io/keybase_amd64.rpm"
  become: true 
  when: "'Fedora' in ansible_distribution"

- name: install keybase DEB
  apt:
    deb: "https://prerelease.keybase.io/keybase_amd64.deb"
  become: true 
  when: "'Ubuntu' in ansible_distribution"