---
- name: install tilix package
  package:
    name:
      - tilix
  become: true

# adjust tilix profile
- name: tilix - background transparency
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent"
    value: "7"

- name: tilix - dim inactive pane
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/dim-transparency-percent"
    value: "40"

- name: tilix - unlimited scrollback
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/scrollback-unlimited"
    value: "true"

- name: tilix - do not show scrollbar
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/show-scrollbar"
    value: "false"

- name: tilix - save window state
  dconf:
    key: "/com/gexperts/Tilix/window-save-state"
    value: "true"

- name: Create fonts directory
  file:
    path: ~/.fonts
    state: directory
    mode: '0750'

- name: install font MesloLGS Regular
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: ~/.fonts/MesloLGS_NF_Regular.ttf
    mode: '0640'
  notify: refresh font cache

- name: tilix - set font to MesloLGS NF 10
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font"
    value: "'MesloLGS NF 10'"

- name: tilix - do not use system font
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-system-font"
    value: "false"

