---
# make this work on armbian, raspbian, or ubuntu arm64 images :)
# may be a little complex on the initial setup of some of these images, since you'll have to log in, set a root password, and then log in as root :(
- name: Install sudo
  apt:
    name: sudo
    state: present
  become: true

- name: Install openssh-server
  apt:
    name: openssh-server
    state: present
  become: true

- name: remove built-in user pi
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
  become: true

- name: remove built-in user ubuntu
  ansible.builtin.user:
    name: ubuntu
    state: absent
    remove: yes
  become: true

- name: Clean up /etc/sudoers.d
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - /etc/sudoers.d/90-cloud-init-users

- name: Add xthor user
  ansible.builtin.user:
    name: xthor
    shell: /bin/bash
  become: true

- name: sudo without password for xthor
  copy:
    content: 'xthor ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/xthor_nopasswd
    validate: 'visudo -cf %s'
    mode: 0440

- name: Set SSH authorized key for xthor
  authorized_key:
    user: xthor
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJNEonif7PNwf6DFR1/nqU9phsdgGFzSMO8EWkD3caLDoAs8/TvnQ+iwvzcox8yAKpU6uIaungjEil3LdiScQSB6yJXB++/4pO827+8AkYmo3seKWkk7LTpHuW8zPc8dbsre1uBCuV7VoAeMJkml1O4wwYooJVt55Nfj2qwVqbg7EMyO9C0KN6X85GLOV1WI3Oa95gmwJvnhg3sbFFW0l4DddsU7rmqzftHyfNzgg/X7VbBa1GzAhhr+EmCh19r8msAgVj6odKutk9/Z8bvE9kUH1+4c0WkdpeVOkdcacluRFZ3lrb9+UTdZ/H1ebTEKbpp/wg7eGT+pO4JcFNrqSqyiVkcBjYi6u8rzCJ3KjSy9718wwWM+y3m/NW0gCuuKTQnCeNqe+b1SUvvPZqGvMykGxStHszkVSDjuGZlu9IsP59ALSWDOvTkybu+fIONw4EmItrdPmGqGHYuA0tTzwLh4QqPr8fvF8sZaVislzHaPWzwaafKc2QpxjoABpfXdU= xthor@spindel.xthorsworld.com"