---
- name: add negativo17 repo (Fedora)
  command:
    cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-multimedia.repo
    creates: /etc/yum.repos.d/fedora-multimedia.repo
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: install makemkv package
  package:
    name:
      - makemkv
    state: present
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: add apt GPG key for hjramses.com makemkv repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9E5738E866C5E6B2
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: add jdramses.com makemkv repo to Debian system
  apt_repository:
    repo: "deb https://ramses.hjramses.com/deb/makemkv {{ ansible_distribution_release }} main"
    state: present
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: install makemkv packages for Debian
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - makemkv-oss
    - makemkv-bin
  become: true
  when: "ansible_distribution == 'Debian'"

- name: Create MakeMKV directory
  file:
    path: ~/.MakeMKV
    state: directory
    mode: '0750'

- name: copy makemkv settings file (unless it already exists)
  copy:
    src: files/settings.conf
    dest: ~/.MakeMKV/settings.conf
    mode: '0660'
    force: no