---
- name: add yum GPG keys from urls
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://negativo17.org/repos/RPM-GPG-KEY-slaanesh"
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: install negativo17 media repo
  yum_repository:
    name: fedora-multimedia
    baseurl: https://negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    enabled: yes
    skip_if_unavailable: yes
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: install makemkv package
  package:
    name:
      - makemkv
    state: present
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: add apt GPG key for hjramses.com makemkv repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9E5738E866C5E6B2
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: add jdramses.com makemkv repo to Debian system
  apt_repository:
    repo: "deb https://ramses.hjramses.com/deb/makemkv {{ ansible_distribution_release }} main"
    state: present
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: install makemkv packages for Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - makemkv-oss
    - makemkv-bin
  become: true
  when: "ansible_distribution == 'Debian'"
