- name: install required xfce packages - Ubuntu/Debian
  become: true
  apt:
    name:
      - arc-theme
      - numix-icon-theme
      - chrome-gnome-shell
  when: ansible_os_family == "Debian"

- name: install required xfce packages - Fedora
  become: true
  package:
    name:
      - chrome-gnome-shell
      - arc-theme
      - numix-icon-theme
  when: "'Fedora' in ansible_distribution"

# xfce terminal settings - these come from a file
#

# xfce interface settings

