---
zabbix_agent_server: aiimon01.american-ins.com
zabbix_agent_serveractive: aiimon01.american-ins.com
zabbix_agent_dont_detect_ip: true
zabbix_agent_become_on_localhost: false
zabbix_api_create_hosts: false
zabbix_agent_link_templates: ["Linux by Zabbix agent"]
zabbix_host_groups: ["Linux servers"]
# without this stuff, auto-creating the host won't work
zabbix_api_server_host: aiimon01.american-ins.com
zabbix_api_server_port: 443
# this user must be added manually before running the playbook. can't figure out a way to add him via ansible, unfortunately.
zabbix_api_http_user: "{{ lookup('community.general.onepassword', 'zabbix_apiuser', field='username', vault='American Insurance') }}"
zabbix_api_http_password: "{{ lookup('community.general.onepassword', 'zabbix_apiuser', field='password', vault='American Insurance') }}"
zabbix_api_use_ssl: yes
zabbix_api_validate_certs: true
ansible_zabbix_url_path: /