---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - ping:

- name: collections
  hosts: localhost
  collections:
    - community.general

- name: Setup personal Linux workstation
  hosts: localhost
  roles:
    - { role: os-packages, tags: [ "os-packages" ] }
    #- { role: ssh, tags: [ "ssh" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: git, tags: [ "git" ] }
    - { role: 1password, tags: [ "1password"] }
    - { role: vscode, tags: [ "vscode"] }
    - { role: zoom, tags: [ "zoom"] }
    - { role: desktop-settings, tags: [ "desktop-settings"] }
    - { role: tilix, tags: [ "tilix" ] }
    - { role: telegram, tags: [ "telegram"] }
    - { role: firefox, tags: [ "firefox"] }
    - { role: podman, tags: [ "podman"] }
    - { role: kubectl, tags: [ "kubectl"] }
    - { role: geerlingguy.helm, tags: [ "helm"] }
    - { role: lefthook, tags: [ "lefthook"] }
    - { role: k9s, tags: [ "k9s"] }
    - { role: awscliv2, tags: [ "awscliv2"] }
    - { role: slack, tags: [ "slack"] }
    - { role: remmina, tags: [ "remmina" ] }
    - { role: terraform, tags: [ "terraform" ] }
    - { role: libvirt, tags: [ "libvirt" ] } # running this last prevents systemd-resolve issues on ubuntu?
