---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - ping:

- name: Setup personal Linux workstation
  hosts: localhost
  roles:
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: kubectl, tags: [ "kubectl" ] }
    - { role: podman, tags: [ "podman" ] }