- hosts: linux
  name: Linux server basic setup
  become: true

  roles:
    - { role: users, tags: [ "users" ] }
    - { role: bash, tags: [ "bash" ] }
    # - { role: community.zabbix.zabbix_agent, tags: [ "zabbix-agent" ] }