---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - name: check sudo
      ping:

- name: Setup Nav Linux workstation
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: gnome-settings, tags: [ "gnome-settings" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: ssh, tags: [ "ssh" ] } # make sure this runs before git on ubuntu, otherwise, github ssh check fails
    - { role: git, tags: [ "git" ] }
    - { role: libvirt, tags: [ "libvirt" ] }
    - { role: conky, tags: [ "conky" ] }
    - { role: pritunl-client, tags: [ "pritunl-client"] }
    - { role: kubectl, tags: [ "kubectl"] }
    - { role: 1password, tags: [ "1password"] }
    - { role: zoom, tags: [ "zoom"] }
    - { role: vscode, tags: [ "vscode"] }
    - { role: keybase, tags: [ "keybase"] }
    - { role: podman, tags: [ "podman"] }
    - { role: google-chrome, tags: [ "google-chrome"] }
