---
- name: Setup personal Linux workstation with Openbox
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: openbox, tags: [ "openbox" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: gitrepos, tags: [ "gitrepos" ] }
    - { role: libvirt, tags: [ "libvirt" ] }
