---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  # doing this prevents a lot of failure messages as all the tasks below execute and fail, too
  tasks:
    - ping:

- name: Setup personal Linux workstation with Openbox
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: openbox, tags: [ "openbox" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: gitrepos, tags: [ "gitrepos" ] }
    - { role: libvirt, tags: [ "libvirt" ] }
