---
- name: Setup personal Linux workstation with Openbox
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: openbox, tags: [ "openbox" ] }
    - { role: terminator, tags: [ "terminator" ] }
