- hosts: proxmox
  name: Setup Proxmox host

  roles:
    #- { role: users, tags: [ "users" ] }
    #- { role: bash, tags: [ "bash" ] }
    #- { role: community.zabbix.zabbix_agent, tags: [ "zabbix-agent" ] }
    - { role: proxmox, tags: [ "proxmox" ] }