---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  # doing this prevents a lot of failure messages as all the tasks below execute and fail, too
  tasks:
    - ping:

- name: Setup a machine to do Handbrake ripping
  hosts: localhost
  roles:
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: gnome-settings, tags: [ "gnome-settings" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: git, tags: [ "git" ] } # TODO: make this check out via HTTPS if the SSH key is not present
    - { role: conky, tags: [ "conky" ] }
    - { role: handbrake, tags: [ "handbrake" ] }
    - { role: makemkv, tags: [ "makemkv" ] }
