---
# this should be called via ansible-pull
# won't have access to secrets, therefore will set temp values till it can be accessed via network
- name: Initial setup for Linux SBC
  hosts: localhost
  roles:
    - { role: users, tags: [ "users"] }
