---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - ping:

- name: set fact for desktop environment
  tasks:
  - set_fact:
     desktop_env: "{{ lookup('env', 'DESKTOP_SESSION' ) | ternary (lookup('env', 'DESKTOP_SESSION' ), omit) }}"

- name: Include role for desktop environment currently running
  tasks:
    - include_role:
        name: gnome-settings
      when: desktop_env == "gnome"
    - include_role:
        name: cinnamon-settings
      when: desktop_env == "cinnamon"
    - include_role:
        name: xfce-settings
      when: desktop_env == "xfce"
    - include_role:
        name: openbox
      when: desktop_env == "openbox"

- name: Setup personal Linux workstation
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: libvirt, tags: [ "libvirt" ] }
    - { role: ssh, tags: [ "ssh" ] }
    - { role: git, tags: [ "git" ] }
    - { role: conky, tags: [ "conky" ] }
    - { role: 1password, tags: [ "1password"] }
    - { role: zoom, tags: [ "zoom"] }
    - { role: vscode, tags: [ "vscode"] }
    - { role: keybase, tags: [ "keybase"] }
    - { role: google-chrome, tags: [ "google-chrome"] }
