---
- name: Setup personal Linux workstation
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: gnome-settings, tags: [ "gnome-settings" ] }
    - { role: terminator, tags: [ "terminator" ] }
