---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - ping:

- name: Setup personal Linux workstation
  hosts: localhost
  roles:
    - { role: os-packages, tags: [ "os-packages" ] }
    - { role: ssh, tags: [ "ssh" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: git, tags: [ "git" ] }
    - { role: 1password, tags: [ "1password"] }
    - { role: vscode, tags: [ "vscode"] }
    - { role: zoom, tags: [ "zoom"] }
    - { role: desktop-settings, tags: [ "desktop-settings"] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: telegram, tags: [ "telegram"] }
    - { role: firefox, tags: [ "firefox"] }
    - { role: spotify, tags: [ "spotify"] }
    - { role: dropbox, tags: [ "dropbox"] }
    - { role: podman, tags: [ "podman"] }
    - { role: kubectl, tags: [ "kubectl"] }
    - { role: awscliv2, tags: [ "awscliv2"] }
    - { role: appimagelauncher, tags: [ "appimagelauncher"] }
    - { role: upnote, tags: [ "upnote"] }
    - { role: conky, tags: [ "conky"] }
    - { role: slack, tags: [ "slack"] }
    - { role: minikube, tags: [ "minikube" ] }
    - { role: oscar, tags: [ "oscar" ] }
    - { role: libvirt, tags: [ "libvirt" ] } # running this last prevents systemd-resolve issues on ubuntu?
