---
- name: verify sudo password
  hosts: localhost
  gather_facts: no
  become: yes
  any_errors_fatal: yes
  tasks:
    - ping:

- name: Setup personal Linux workstation (XFCE DE)
  hosts: localhost
  roles:
    - { role: tools, tags: [ "tools" ] }
    - { role: oh-my-zsh, tags: [ "oh-my-zsh" ] }
#    - { role: xfce-settings, tags: [ "xfce-settings" ] }
    - { role: terminator, tags: [ "terminator" ] }
    - { role: power-management, tags: [ "power-management" ] }
    - { role: vim, tags: [ "vim" ] }
    - { role: libvirt, tags: [ "libvirt" ] }
    - { role: ssh, tags: [ "ssh" ] }
    - { role: git, tags: [ "git" ] }
    - { role: conky, tags: [ "conky" ] }
    - { role: 1password, tags: [ "1password"] }
    - { role: zoom, tags: [ "zoom"] }
    - { role: vscode, tags: [ "vscode"] }
    - { role: keybase, tags: [ "keybase"] }
    - { role: google-chrome, tags: [ "google-chrome"] }
