  - hosts: zabbix-servers
    become: true

    roles:
      - role: geerlingguy.repo-epel
        when: ansible_os_family == "RedHat"
      #- role: geerlingguy.repo-remi
      #  when: ansible_os_family == "RedHat"
      - geerlingguy.mysql
      - geerlingguy.apache
      - geerlingguy.php
      - community.zabbix.zabbix_server
      - community.zabbix.zabbix_web
      - community.zabbix.zabbix_agent