  - hosts: zabbix_servers
    become: true

    roles:
      - role: users
      - role: bash
      - role: geerlingguy.repo-epel
        when: ansible_os_family == "RedHat"
      - role: zabbix-pre
      - role: ssl-cert
        tags: ["ssl-cert"]
        when: san_name is defined
      - geerlingguy.mysql
      - geerlingguy.apache
      - role: geerlingguy.certbot
        when: certbot_admin_email is defined
      - geerlingguy.php
      - community.zabbix.zabbix_server
      - role: community.zabbix.zabbix_web
        tags: ["zabbix-web"]
      - role: community.zabbix.zabbix_agent
        tags: ["zabbix-agent"]