---
- name: install nautilus-dropbox (Fedora)
  yum:
    name: nautilus-dropbox
    state: present
  become: true 
  when: ansible_distribution == "Fedora"

- name: Install dropbox (Rocky Linux)
  yum:
    name: https://linux.dropbox.com/packages/fedora/nautilus-dropbox-2020.03.04-1.fedora.x86_64.rpm
  become: true
  when: ansible_distribution == "Rocky"

- name: install deb for dropbox
  apt:
    deb: "https://linux.dropbox.com/packages/ubuntu/dropbox_2020.03.04_amd64.deb"
  become: true
  when: "'Debian' in ansible_os_family"

- name: install python3-gpg on for dropbox
  package:
    name: python3-gpg
    state: present
  become: true
