---
- name: Ensure locale en_US.UTF-8 exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure cron is installed and present
  package:
    name:
      - cron
  become: true