- name: add apt GPG key for filebot repo
  apt_key:
    url: https://get.filebot.net/filebot/KEYS
    state: present
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: add filebot repo to Debian system
  apt_repository:
    repo: "deb [arch=all] https://get.filebot.net/deb/ universal main"
    state: present
  become: true 
  when: "ansible_distribution == 'Debian'"

- name: install filebot package for Debian
  apt:
    name: filebot
    state: present
  become: true
  when: "ansible_distribution == 'Debian'"

- name: Add FileBot repo (Fedora)
  command:
    cmd: sudo dnf config-manager --add-repo 'https://raw.githubusercontent.com/filebot/plugins/master/yum/main.repo'
    creates: /etc/yum.repos.d/main.repo
  become: true
  when: ansible_distribution == "Fedora"

- name: install FileBot package and dependencies (Fedora)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - filebot
    - zenity
  become: true
  when: ansible_distribution == "Fedora"