---
- name: Add lefthook repo to Fedora
  command:
    cmd: curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.rpm.sh' | bash
    creates: /etc/yum.repos.d/evilmartians-lefthook.repo
  become: true
  when: "ansible_distribution == 'Fedora'"

- name: Add lefthook repo to Ubuntu and friends
  command:
    cmd: curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.deb.sh' | bash
    creates: /etc/apt/sources.list.d/evilmartians-lefthook.list
  become: true
  when: ansible_os_family == "Debian"

- name: install lefthook package
  package:
    name: lefthook
    state: present
  become: true
